"""Core domain: foundational application configuration, logging, and data type contracts."""

from __future__ import annotations

from .config import (
    AppSettings,
    PalWorldIniSettingsSource,
    get_settings,
    is_posix,
    reload_settings,
    resolve_host_lan_ip,
    resolve_palworld_ini_path,
)
from .logger import (
    DiscordLogHandler,
    SensitiveDataFilter,
    log,
    parse_discord_retry_after,
    sanitize_log_text,
    setup_logger,
)
from .types import (
    CombinedTelemetryPayload,
    DiscoveryHubPayload,
    EngineMetrics,
    GitCommitInfo,
    HardwareTelemetryInfo,
    LifecycleState,
    LogScraperInfo,
    NetworkDiagnosticsResult,
    NetworkMatrixInfo,
    PlayerCoordinates,
    PlayerLedgerMatrix,
    PlayerRecord,
    PocketpairMasterInfo,
    ReadinessInfo,
    SecurityMatrixInfo,
    SteamA2SInfo,
    TopBadgeInfo,
)

__all__ = [
    "AppSettings",
    "CombinedTelemetryPayload",
    "DiscordLogHandler",
    "DiscoveryHubPayload",
    "EngineMetrics",
    "GitCommitInfo",
    "HardwareTelemetryInfo",
    "LifecycleState",
    "LogScraperInfo",
    "NetworkDiagnosticsResult",
    "NetworkMatrixInfo",
    "PalWorldIniSettingsSource",
    "PlayerCoordinates",
    "PlayerLedgerMatrix",
    "PlayerRecord",
    "PocketpairMasterInfo",
    "ReadinessInfo",
    "SecurityMatrixInfo",
    "SensitiveDataFilter",
    "SteamA2SInfo",
    "TopBadgeInfo",
    "get_settings",
    "is_posix",
    "log",
    "parse_discord_retry_after",
    "reload_settings",
    "resolve_host_lan_ip",
    "resolve_palworld_ini_path",
    "sanitize_log_text",
    "setup_logger",
]
